// Code generated by goyacc - DO NOT EDIT.

package configparser

import __yyfmt__ "fmt"

import (
	"fmt"
	"time"

	"github.com/PlakarKorp/plakar/scheduler"
)

func Parser(lexer yyLexer) *ConfigParser {
	return lexer.(*ConfigParser)
}

type yySymType struct {
	yys       int
	b         bool
	s         string
	i         int64
	task      scheduler.Task
	schedule  scheduler.Schedule
	schedules []scheduler.Schedule
	times     []scheduler.Time
	strings   []string
	size      float64
	duration  time.Duration
	time      scheduler.Time
	datemask  scheduler.DateMask
	month     time.Month
	err       error
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault   = 57384
	yyEofCode   = 57344
	AND         = 57368
	AT          = 57370
	BACKUP      = 57349
	BEFORE      = 57361
	CATEGORY    = 57355
	CHECK       = 57350
	DAY         = 57369
	DURATION    = 57378
	ENVIRONMENT = 57356
	ERROR       = 57376
	EVERY       = 57371
	EXCLUDE     = 57363
	FROM        = 57365
	INTEGER     = 57373
	JOB         = 57358
	LATEST      = 57360
	MAINTENANCE = 57353
	MONTH       = 57381
	NAME        = 57354
	OFF         = 57348
	ON          = 57347
	PERIMETER   = 57357
	REFERENCE   = 57375
	REPORTING   = 57346
	RESTORE     = 57351
	RETENTION   = 57364
	SINCE       = 57362
	SIZE        = 57377
	STRING      = 57374
	SYNC        = 57352
	TAG         = 57359
	TIME        = 57379
	TO          = 57366
	UNTIL       = 57372
	WEEKDAY     = 57380
	WITH        = 57367
	yyErrCode   = 57345

	yyMaxDepth = 200
	yyTabOfs   = -55
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57370: 0,  // AT (37x)
		57371: 1,  // EVERY (37x)
		57344: 2,  // $end (26x)
		57358: 3,  // JOB (26x)
		57346: 4,  // REPORTING (26x)
		57374: 5,  // STRING (15x)
		57347: 6,  // ON (13x)
		44:    7,  // ',' (11x)
		57375: 8,  // REFERENCE (11x)
		57363: 9,  // EXCLUDE (10x)
		57359: 10, // TAG (10x)
		57366: 11, // TO (7x)
		57397: 12, // repository (6x)
		57365: 13, // FROM (5x)
		57372: 14, // UNTIL (5x)
		57379: 15, // TIME (4x)
		57408: 16, // time (4x)
		57367: 17, // WITH (3x)
		57398: 18, // schedule (2x)
		57401: 19, // schedule_time (2x)
		57380: 20, // WEEKDAY (2x)
		57411: 21, // weekday (2x)
		57382: 22, // $@1 (1x)
		57383: 23, // $@2 (1x)
		57349: 24, // BACKUP (1x)
		57385: 25, // backup_opt (1x)
		57386: 26, // backup_opts (1x)
		57350: 27, // CHECK (1x)
		57387: 28, // destination (1x)
		57388: 29, // duration (1x)
		57378: 30, // DURATION (1x)
		57389: 31, // from_time (1x)
		57390: 32, // grammar (1x)
		57391: 33, // job (1x)
		57353: 34, // MAINTENANCE (1x)
		57348: 35, // OFF (1x)
		57395: 36, // on_off (1x)
		57396: 37, // reporting (1x)
		57351: 38, // RESTORE (1x)
		57399: 39, // schedule_days (1x)
		57400: 40, // schedule_list (1x)
		57403: 41, // source (1x)
		57405: 42, // string_list (1x)
		57352: 43, // SYNC (1x)
		57406: 44, // sync_direction (1x)
		57407: 45, // task (1x)
		57409: 46, // time_list (1x)
		57410: 47, // until_time (1x)
		57412: 48, // weekday_list (1x)
		57384: 49, // $default (0x)
		57368: 50, // AND (0x)
		57361: 51, // BEFORE (0x)
		57355: 52, // CATEGORY (0x)
		57369: 53, // DAY (0x)
		57356: 54, // ENVIRONMENT (0x)
		57345: 55, // error (0x)
		57376: 56, // ERROR (0x)
		57373: 57, // INTEGER (0x)
		57360: 58, // LATEST (0x)
		57392: 59, // maintenance_opt (0x)
		57393: 60, // maintenance_opts (0x)
		57381: 61, // MONTH (0x)
		57394: 62, // month (0x)
		57354: 63, // NAME (0x)
		57357: 64, // PERIMETER (0x)
		57364: 65, // RETENTION (0x)
		57362: 66, // SINCE (0x)
		57402: 67, // size (0x)
		57377: 68, // SIZE (0x)
		57404: 69, // source_list (0x)
	}

	yySymNames = []string{
		"AT",
		"EVERY",
		"$end",
		"JOB",
		"REPORTING",
		"STRING",
		"ON",
		"','",
		"REFERENCE",
		"EXCLUDE",
		"TAG",
		"TO",
		"repository",
		"FROM",
		"UNTIL",
		"TIME",
		"time",
		"WITH",
		"schedule",
		"schedule_time",
		"WEEKDAY",
		"weekday",
		"$@1",
		"$@2",
		"BACKUP",
		"backup_opt",
		"backup_opts",
		"CHECK",
		"destination",
		"duration",
		"DURATION",
		"from_time",
		"grammar",
		"job",
		"MAINTENANCE",
		"OFF",
		"on_off",
		"reporting",
		"RESTORE",
		"schedule_days",
		"schedule_list",
		"source",
		"string_list",
		"SYNC",
		"sync_direction",
		"task",
		"time_list",
		"until_time",
		"weekday_list",
		"$default",
		"AND",
		"BEFORE",
		"CATEGORY",
		"DAY",
		"ENVIRONMENT",
		"error",
		"ERROR",
		"INTEGER",
		"LATEST",
		"maintenance_opt",
		"maintenance_opts",
		"MONTH",
		"month",
		"NAME",
		"PERIMETER",
		"RETENTION",
		"SINCE",
		"size",
		"SIZE",
		"source_list",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {32, 0},
		2:  {32, 2},
		3:  {32, 2},
		4:  {37, 2},
		5:  {33, 4},
		6:  {22, 0},
		7:  {45, 6},
		8:  {45, 2},
		9:  {23, 0},
		10: {45, 4},
		11: {45, 4},
		12: {45, 4},
		13: {41, 1},
		14: {41, 1},
		15: {69, 1},
		16: {69, 2},
		17: {28, 1},
		18: {28, 1},
		19: {12, 1},
		20: {12, 1},
		21: {26, 0},
		22: {26, 2},
		23: {25, 2},
		24: {25, 2},
		25: {60, 0},
		26: {60, 2},
		27: {59, 0},
		28: {44, 1},
		29: {44, 1},
		30: {44, 1},
		31: {40, 1},
		32: {40, 2},
		33: {18, 2},
		34: {19, 2},
		35: {19, 4},
		36: {31, 0},
		37: {31, 2},
		38: {47, 0},
		39: {47, 2},
		40: {39, 0},
		41: {39, 2},
		42: {48, 1},
		43: {48, 3},
		44: {46, 1},
		45: {46, 3},
		46: {42, 1},
		47: {42, 3},
		48: {67, 1},
		49: {29, 1},
		50: {16, 1},
		51: {21, 1},
		52: {62, 1},
		53: {36, 1},
		54: {36, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [74][]uint16{
		// 0
		{2: 54, 54, 54, 32: 56},
		{2: 55, 60, 59, 33: 58, 37: 57},
		{2: 53, 53, 53},
		{2: 52, 52, 52},
		{6: 127, 35: 128, 126},
		// 5
		{5: 61},
		{24: 63, 27: 64, 34: 65, 38: 66, 43: 67, 45: 62},
		{103, 104, 18: 101, 102, 40: 100},
		{5: 86, 8: 87, 41: 85},
		{5: 69, 8: 70, 12: 84},
		// 10
		{6: 81},
		{5: 69, 8: 70, 12: 76},
		{5: 69, 8: 70, 12: 68},
		{11: 72, 13: 73, 17: 74, 44: 71},
		{36, 36, 9: 36, 36, 36, 13: 36, 17: 36},
		// 15
		{35, 35, 9: 35, 35, 35, 13: 35, 17: 35},
		{5: 69, 8: 70, 12: 75},
		{5: 27, 8: 27},
		{5: 26, 8: 26},
		{5: 25, 8: 25},
		// 20
		{43, 43},
		{11: 77},
		{5: 79, 8: 80, 28: 78},
		{44, 44},
		{38, 38},
		// 25
		{37, 37},
		{5: 69, 8: 70, 12: 82},
		{46, 46, 23: 83},
		{45, 45},
		{47, 47},
		// 30
		{11: 88},
		{11: 42},
		{11: 41},
		{5: 69, 8: 70, 12: 89},
		{49, 49, 9: 49, 49, 22: 90},
		// 35
		{34, 34, 9: 34, 34, 26: 91},
		{48, 48, 9: 94, 93, 25: 92},
		{33, 33, 9: 33, 33},
		{5: 97, 42: 96},
		{5: 95},
		// 40
		{31, 31, 9: 31, 31},
		{32, 32, 7: 98, 9: 32, 32},
		{9, 9, 7: 9, 9: 9, 9},
		{5: 99},
		{8, 8, 7: 8, 9: 8, 8},
		// 45
		{103, 104, 50, 50, 50, 18: 125, 102},
		{24, 24, 24, 24, 24},
		{15, 15, 15, 15, 15, 6: 119, 39: 118},
		{15: 110, 115, 46: 114},
		{29: 105, 106},
		// 50
		{19, 19, 19, 19, 19, 6: 19, 13: 108, 19, 31: 107},
		{6, 6, 6, 6, 6, 6: 6, 13: 6, 6},
		{17, 17, 17, 17, 17, 6: 17, 14: 112, 47: 111},
		{15: 110, 109},
		{18, 18, 18, 18, 18, 6: 18, 14: 18},
		// 55
		{5, 5, 5, 5, 5, 6: 5, 5, 14: 5},
		{20, 20, 20, 20, 20, 6: 20},
		{15: 110, 113},
		{16, 16, 16, 16, 16, 6: 16},
		{21, 21, 21, 21, 21, 6: 21, 116},
		// 60
		{11, 11, 11, 11, 11, 6: 11, 11},
		{15: 110, 117},
		{10, 10, 10, 10, 10, 6: 10, 10},
		{22, 22, 22, 22, 22},
		{20: 122, 121, 48: 120},
		// 65
		{14, 14, 14, 14, 14, 7: 123},
		{13, 13, 13, 13, 13, 7: 13},
		{4, 4, 4, 4, 4, 7: 4},
		{20: 122, 124},
		{12, 12, 12, 12, 12, 7: 12},
		// 70
		{23, 23, 23, 23, 23},
		{2: 51, 51, 51},
		{2: 2, 2, 2},
		{2: 1, 1, 1},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 55

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 4:
		{
			Parser(yylex).reporting = yyS[yypt-0].b
		}
	case 5:
		{
			if Parser(yylex).HasJob(yyS[yypt-2].s) {
				Parser(yylex).Error(fmt.Sprintf("job %q already defined", yyS[yypt-2].s))
				goto ret1
			}
			Parser(yylex).PushJob(yyS[yypt-2].s, yyS[yypt-1].task, yyS[yypt-0].schedules)
		}
	case 6:
		{
			Parser(yylex).MakeBackupTask(yyS[yypt-0].s, yyS[yypt-2].s)
		}
	case 7:
		{
			yyVAL.task = Parser(yylex).currentTask
		}
	case 8:
		{
			yyVAL.task = Parser(yylex).MakeCheckTask(yyS[yypt-0].s)
		}
	case 9:
		{
			Parser(yylex).MakeMaintenanceTask(yyS[yypt-0].s)
		}
	case 10:
		{
			yyVAL.task = Parser(yylex).currentTask
		}
	case 11:
		{
			yyVAL.task = Parser(yylex).MakeRestoreTask(yyS[yypt-2].s, yyS[yypt-0].s)
		}
	case 12:
		{
			yyVAL.task = Parser(yylex).MakeSyncTask(yyS[yypt-2].s, yyS[yypt-1].s, yyS[yypt-0].s)
		}
	case 13:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 14:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 15:
		{
			yyVAL.strings = append(make([]string, 0, 5), yyS[yypt-0].s)
		}
	case 16:
		{
			yyVAL.strings = append(yyS[yypt-1].strings, yyS[yypt-0].s)
		}
	case 17:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 18:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 19:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 20:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 23:
		{
			task := Parser(yylex).currentTask.(*scheduler.BackupTask)
			task.Cmd.Tags = yyS[yypt-0].strings
		}
	case 24:
		{
			task := Parser(yylex).currentTask.(*scheduler.BackupTask)
			task.Cmd.Excludes = append(task.Cmd.Excludes, yyS[yypt-0].s)
		}
	case 28:
		{
			yyVAL.s = "to"
		}
	case 29:
		{
			yyVAL.s = "from"
		}
	case 30:
		{
			yyVAL.s = "with"
		}
	case 31:
		{
			yyVAL.schedules = append(yyVAL.schedules, yyS[yypt-0].schedule)
		}
	case 32:
		{
			yyVAL.schedules = append(yyS[yypt-1].schedules, yyS[yypt-0].schedule)
		}
	case 33:
		{
			yyVAL.schedule = yyS[yypt-1].schedule.WithDateMask(yyS[yypt-0].datemask)
		}
	case 34:
		{
			yyVAL.schedule = Parser(yylex).MakeScheduleAt(yyS[yypt-0].times)
		}
	case 35:
		{
			yyVAL.schedule = Parser(yylex).MakeScheduleEvery(yyS[yypt-2].duration, yyS[yypt-1].time, yyS[yypt-0].time)
		}
	case 36:
		{
			yyVAL.time = scheduler.UndefinedTime
		}
	case 37:
		{
			yyVAL.time = yyS[yypt-0].time
		}
	case 38:
		{
			yyVAL.time = scheduler.UndefinedTime
		}
	case 39:
		{
			yyVAL.time = yyS[yypt-0].time
		}
	case 40:
		{
			yyVAL.datemask = scheduler.EveryDay
		}
	case 41:
		{
			yyVAL.datemask = scheduler.EveryDay.SetWeekdayMask(yyS[yypt-0].datemask)
		}
	case 42:
		{
			yyVAL.datemask = yyS[yypt-0].datemask
		}
	case 43:
		{
			yyVAL.datemask = yyS[yypt-2].datemask | yyS[yypt-0].datemask
		}
	case 44:
		{
			yyVAL.times = append(make([]scheduler.Time, 0, 1), yyS[yypt-0].time)
		}
	case 45:
		{
			yyVAL.times = append(yyS[yypt-2].times, yyS[yypt-0].time)
		}
	case 46:
		{
			yyVAL.strings = append(make([]string, 0, 1), yyS[yypt-0].s)
		}
	case 47:
		{
			yyVAL.strings = append(yyS[yypt-2].strings, yyS[yypt-0].s)
		}
	case 48:
		{
			yyVAL.size = yyS[yypt-0].size
		}
	case 49:
		{
			yyVAL.duration = yyS[yypt-0].duration
		}
	case 50:
		{
			yyVAL.time = yyS[yypt-0].time
		}
	case 51:
		{
			yyVAL.datemask = yyS[yypt-0].datemask
		}
	case 52:
		{
			yyVAL.month = yyS[yypt-0].month
		}
	case 53:
		{
			yyVAL.b = true
		}
	case 54:
		{
			yyVAL.b = false
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
